#!/bin/sh

#
# This script makes it easy and
# possible to excute the binary
# sample from anywhere in the system.
# You won't have to be in a particular
# directory to execute the sample.

#
# Give the server the argument of 
# the path to the serverconfig.properties
# file 
#

/usr/local/share/librebecca/bin/rebecca-server --Ice.Config=/usr/local/share/librebecca/conf/serverconfig.properties

